version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_modelos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL= "postgres://admin:1234@db:5432/db_modelos"
volumes:
  postgres_data:
