version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: proyectoML%
      POSTGRES_DB: db_modelos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://administrador:proyectoML%@db:5432/db_modelos
    depends_on:
      - db
    ports:
      - "8000:80"

volumes:
  postgres_data:
